# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.3.0"

    steps:
      - checkout

      # build dependencies if the cached dependencies are out of date
      - restore_cache:
          key: 1-charthage-{{ checksum "Cartfile.resolved" }}
      - run:
          name: build dependencies if the cached dependencies are out of date
          command: bin/bootstrap-if-needed
      - save_cache:
          key: 1-charthage-{{ checksum "Cartfile.resolved" }}
          paths:
            - Carthage

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone X
            SCAN_SCHEME: RxSwiftRailsTutorial

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.html
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs


